#!/usr/bin/env perl

use Catmandu::Importer::Purr;

my $purr = Catmandu::Importer::Purr->new;
my $date = localtime;

print "<!-- autogenerated on $date by purr -->\n";
print "<ul style=\"list-style-type:none;\">\n";

for (sort { $a->{distribution} cmp $b->{distribution} } @{$purr->to_array} ) {
   my $module = $_->{distribution};
   $module =~ s/-/::/g;
   printf "<li><a href=\"https://metacpan.org/pod/%s\">%s</a> - %s</li>\n" 
                , $module 
                , $_->{distribution} 
                , $_->{version};
}

print "</ul>"

